# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://zulip.csatnyu.com
title: CS@NYU
email: andrew.drozdov@nyu.edu
author: CS@NYU
description: > # "CS@NYU is a community for NYU Compute Science
  students. Conversations are focused on technical tips, news and
  events. The platform uses Zulip, a wonderful open source group
  chat."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/CSAtNYU
  - title: email
    url: mailto:andrew.drozdov@nyu.edu
